name: common
version: "0.1"

dependencies:
  - base
  - lens
  - text
  - nat
  - containers

source-dirs: src

library:
  exposed-modules:
    - Common.Api
    - Common.DiceSet

tests:
  tests:
    main: Main.hs
    source-dirs:
      - tests
    dependencies:
      - tasty
      - tasty-discover
      - tasty-hunit
